const cards = [
    {
        name: "CAH Base Set",
        white: [
            { text: '"Tweeting."', pack: 0 },
            { text: "100% Pure New Zealand.", pack: 0 },
            { text: "2 Girls 1 Cup.", pack: 0 },
            { text: "50 mg of Zoloft daily.", pack: 0 },
            { text: "50,000 volts straight to the nipples.", pack: 0 },
            { text: "8 oz. of sweet Mexican black-tar heroin.", pack: 0 },
            { text: "A bag of magic beans.", pack: 0 },
            { text: "A balanced breakfast.", pack: 0 },
            { text: "A big hoopla about nothing.", pack: 0 },
            { text: "A bowl of mayonnaise and human teeth.", pack: 0 },
            { text: "A brain tumor.", pack: 0 },
            { text: "A bucket of fish heads.", pack: 0 },
            { text: "A can of whoop-ass.", pack: 0 },
            {
                text: "A Chinese tourist who wants something very badly but cannot communicate it.",
                pack: 0,
            },
            { text: "A cooler full of organs.", pack: 0 },
            { text: "A copy of Bedside Hitler.", pack: 0 },
            { text: "A crucifixion.", pack: 0 },
            { text: "A decent fucking Internet connection.", pack: 0 },
            { text: "A disappointing birthday party.", pack: 0 },
            { text: "A drive-by shooting.", pack: 0 },
            { text: "A fanny fart.", pack: 0 },
            {
                text: "A fart so powerful that it wakes the giants from their thousand-year slumber.",
                pack: 0,
            },
            { text: "A fat bald man from the internet.", pack: 0 },
            { text: "A foul mouth.", pack: 0 },
            { text: "A gassy antelope.", pack: 0 },
            { text: "A good sniff.", pack: 0 },
            { text: "A good, strong gorilla.", pack: 0 },
            {
                text: "A grande sugar-free iced soy caramel macchiato.",
                pack: 0,
            },
            { text: "A Gypsy curse.", pack: 0 },
            { text: "A hairless little shitstain named Callou.", pack: 0 },
            { text: "A Halal Snack Pack.", pack: 0 },
            { text: "A hen night in Slough.", pack: 0 },
            { text: "A horde of Vikings.", pack: 0 },
            { text: "A hot mess.", pack: 0 },
            {
                text: "A Japanese tourist who wants something very badly but cannot communicate it.",
                pack: 0,
            },
            { text: "A Japanese whaling operation.", pack: 0 },
            { text: "A LAN party.", pack: 0 },
            { text: "A lifetime of sadness.", pack: 0 },
            { text: "A literal tornado of fire.", pack: 0 },
            {
                text: "A little boy who won't shut the fuck up about dinosaurs.",
                pack: 0,
            },
            { text: "A live studio audience.", pack: 0 },
            { text: "A look-see.", pack: 0 },
            { text: "A low standard of living.", pack: 0 },
            { text: "A mad cow.", pack: 0 },
            {
                text: "A madman who lives in a police box and kidnaps women.",
                pack: 0,
            },
            { text: "A man of means by no means.", pack: 0 },
            { text: "A mating display.", pack: 0 },
            { text: "A Mexican.", pack: 0 },
            {
                text: "A micropig wearing a tiny raincoat and booties.",
                pack: 0,
            },
            { text: "A middle-aged man on roller skates.", pack: 0 },
            { text: "A mime having a stroke.", pack: 0 },
            { text: "A moment of silence.", pack: 0 },
            { text: "A monkey smoking a cigar.", pack: 0 },
            { text: "A mopey zoo lion.", pack: 0 },
            { text: "A much younger woman.", pack: 0 },
            { text: "A murder most foul.", pack: 0 },
            { text: "A neglected Tamagotchi™.", pack: 0 },
            { text: "A nice cup of tea.", pack: 0 },
            { text: "A pyramid of severed heads.", pack: 0 },
            { text: "A really cool hat.", pack: 0 },
            { text: "A robust mongoloid.", pack: 0 },
            { text: "A salad for men that's made of metal.", pack: 0 },
            { text: "A salty surprise.", pack: 0 },
            { text: "A sassy black woman.", pack: 0 },
            { text: "A sausage festival.", pack: 0 },
            { text: "A saxophone solo.", pack: 0 },
            { text: "A sea of troubles.", pack: 0 },
            { text: "A shark!", pack: 0 },
            { text: "A sick burnout.", pack: 0 },
            { text: "A sick wombat.", pack: 0 },
            { text: "A sickly child-king.", pack: 0 },
            { text: "A six-point plan to stop the boats.", pack: 0 },
            {
                text: "A sober Irishman who doesn't care for potatoes.",
                pack: 0,
            },
            { text: "A soggy Sao.", pack: 0 },
            { text: "A spastic nerd.", pack: 0 },
            { text: "A subscription to Men's Fitness.", pack: 0 },
            { text: "A surprisingly low amount of prison rape.", pack: 0 },
            { text: "A thermonuclear detonation.", pack: 0 },
            {
                text: "A thousand Scottish warriors lifting their kilts in unison.",
                pack: 0,
            },
            { text: "A Tim Hortons franchise.", pack: 0 },
            { text: "A time travel paradox.", pack: 0 },
            { text: "A tiny horse.", pack: 0 },
            { text: "A tiny, gay guitar called a ukulele.", pack: 0 },
            { text: "A tribe of warrior women.", pack: 0 },
            { text: "A vastly superior healthcare system.", pack: 0 },
            { text: "A web of lies.", pack: 0 },
            { text: "A wheelchair death race.", pack: 0 },
            { text: "A white ethnostate.", pack: 0 },
            { text: "A white van man.", pack: 0 },
            { text: "A windmill full of corpses.", pack: 0 },
            { text: "A wisecracking terrorist.", pack: 0 },
            { text: "A zesty breakfast burrito.", pack: 0 },
            { text: "Aaron Burr.", pack: 0 },
            { text: "Abstinence.", pack: 0 },
            { text: "Academy Award winner Meryl Streep.", pack: 0 },
            { text: "Accepting the way things are.", pack: 0 },
            { text: "Accidentally slipping yourself a roofie.", pack: 0 },
            { text: "Active listening.", pack: 0 },
            { text: "Actually giving a shit", pack: 0 },
            { text: "Adderall™.", pack: 0 },
            { text: "Adult Friendfinder.", pack: 0 },
            { text: "Advice from a wise, old black man.", pack: 0 },
            { text: "African children.", pack: 0 },
            { text: "Agriculture.", pack: 0 },
            { text: "Alcohol poisoning.", pack: 0 },
            { text: "Alcoholism.", pack: 0 },
            { text: "All my gentleman suitors.", pack: 0 },
            { text: "all pants are half off today", pack: 0 },
            { text: "All-you-can-eat shrimp for $8.99.", pack: 0 },
            { text: "Altar boys.", pack: 0 },
            { text: "America.", pack: 0 },
            { text: "American Gladiators.", pack: 0 },
            { text: "Americanization.", pack: 0 },
            { text: "Amputees.", pack: 0 },
            { text: "An AK-47 assault rifle.", pack: 0 },
            { text: "An AK-47.", pack: 0 },
            { text: "An AR-15 assault rifle.", pack: 0 },
            { text: "An argument with Richard Dawkins.", pack: 0 },
            { text: "An ass like two football helmets.", pack: 0 },
            { text: "An asymmetric boob job.", pack: 0 },
            { text: "An endless stream of diarrhea.", pack: 0 },
            { text: "An entrenched class system.", pack: 0 },
            { text: "An Evening with Michael Buble.", pack: 0 },
            { text: "An evil man in evil clothes.", pack: 0 },
            { text: "An honest cop with nothing left to lose.", pack: 0 },
            { text: "An icepick lobotomy.", pack: 0 },
            { text: "An M. Night Shyamalan plot twist.", pack: 0 },
            { text: "An M16 assault rifle.", pack: 0 },
            { text: "An Oedipus complex.", pack: 0 },
            { text: "An old guy who's almost dead.", pack: 0 },
            { text: "An oversized lollipop.", pack: 0 },
            { text: "An ugly face.", pack: 0 },
            { text: "An unsurprising rash.", pack: 0 },
            { text: "An uppercut.", pack: 0 },
            { text: "Another goddamn vampire movie.", pack: 0 },
            {
                text: "Anything that comes out of Prince Philip's mouth.",
                pack: 0,
            },
            { text: "Apologizing.", pack: 0 },
            { text: "Attitude.", pack: 0 },
            { text: "Auschwitz.", pack: 0 },
            { text: "Australia.", pack: 0 },
            { text: "Authentic Mexican cuisine.", pack: 0 },
            { text: "Autocannibalism.", pack: 0 },
            { text: "AXE Body Spray.", pack: 0 },
            { text: "Bananas in Pajamas.", pack: 0 },
            { text: "Bananas.", pack: 0 },
            { text: "Barack Obama.", pack: 0 },
            { text: "Barely making $25,000 a year.", pack: 0 },
            { text: "Basic trainees.", pack: 0 },
            { text: "BATMAN!!!", pack: 0 },
            { text: "Battlefield amputations.", pack: 0 },
            { text: "Becoming a blueberry.", pack: 0 },
            { text: "Bees?", pack: 0 },
            {
                text: "Being a busy adult with many important things to do.",
                pack: 0,
            },
            { text: "Being a dick to children.", pack: 0 },
            { text: "Being a dinosaur.", pack: 0 },
            {
                text: "Being a hideous beast that no one could love.",
                pack: 0,
            },
            { text: "Being a motherfucking sorcerer.", pack: 0 },
            { text: "Being a woman.", pack: 0 },
            { text: "Being able to talk to elephants.", pack: 0 },
            { text: "Being back-to-back World War Champions!", pack: 0 },
            { text: "Being black.", pack: 0 },
            { text: "Being Canadian.", pack: 0 },
            { text: "Being fabulous.", pack: 0 },
            { text: "Being fat and stupid.", pack: 0 },
            { text: "Being hunted like a fox.", pack: 0 },
            { text: "Being marginalized.", pack: 0 },
            { text: "Being on fire.", pack: 0 },
            { text: "Being rich.", pack: 0 },
            { text: "Being white.", pack: 0 },
            { text: "Benedict Cumberbatch.", pack: 0 },
            {
                text: "Bio-engineered assault turtles with acid breath.",
                pack: 0,
            },
            { text: "Bisexuality.", pack: 0 },
            { text: "Bling.", pack: 0 },
            { text: "Blowing up Parliament.", pack: 0 },
            { text: "Boat people; half boat, half human.", pack: 0 },
            { text: "Bogies.", pack: 0 },
            { text: "Bond, James Bond.", pack: 0 },
            { text: "Bono.", pack: 0 },
            { text: "Bosnian chicken farmers.", pack: 0 },
            { text: "Breaking out into song and dance.", pack: 0 },
            { text: "Brexit.", pack: 0 },
            { text: "Britney Spears at 55.", pack: 0 },
            { text: "Brown people.", pack: 0 },
            { text: "Burning down the White House.", pack: 0 },
            {
                text: "Buying the right toothbrush cup for my lifestyle.",
                pack: 0,
            },
            { text: "Canada: America's Hat.", pack: 0 },
            { text: "Canadian Netflix.", pack: 0 },
            { text: "Canned tuna with extra dolphin.", pack: 0 },
            {
                text: "Capturing Newt Gingrich and forcing him to dance in a monkey suit.",
                pack: 0,
            },
            { text: "Cardi B.", pack: 0 },
            { text: "Cashed-up bogans.", pack: 0 },
            { text: "Catapults.", pack: 0 },
            { text: "Centaurs.", pack: 0 },
            { text: "Chainsaws for hands.", pack: 0 },
            { text: "Charisma.", pack: 0 },
            { text: "Cheating in the Paralympics.", pack: 0 },
            { text: "Cheating in the Special Olympics.", pack: 0 },
            { text: "Chemical weapons.", pack: 0 },
            { text: "Child abuse.", pack: 0 },
            { text: "Child beauty pageants.", pack: 0 },
            { text: "Children on leashes.", pack: 0 },
            { text: "Chivalry.", pack: 0 },
            { text: "Christopher Walken.", pack: 0 },
            { text: "Chunks of dead backpacker.", pack: 0 },
            { text: "Chunks of dead hitchhiker.", pack: 0 },
            { text: "Chunks of dead prostitute.", pack: 0 },
            { text: "Civilian casualties.", pack: 0 },
            { text: "Classist undertones.", pack: 0 },
            { text: "Clive Palmer's soft, shitty body.", pack: 0 },
            { text: "Clubbing baby seals.", pack: 0 },
            { text: "Coat hanger abortions.", pack: 0 },
            { text: "Cockfights.", pack: 0 },
            { text: "College.", pack: 0 },
            { text: "Committing suicide.", pack: 0 },
            { text: "Completely unwarranted confidence.", pack: 0 },
            { text: "Consensual sex.", pack: 0 },
            { text: "Consultants.", pack: 0 },
            { text: "Converting to Islam.", pack: 0 },
            {
                text: "Cookie Monster devouring the Eucharist wafers.",
                pack: 0,
            },
            { text: "Copping a feel.", pack: 0 },
            { text: "Cottaging.", pack: 0 },
            { text: "Court-ordered rehab.", pack: 0 },
            {
                text: "Covering myself with Parmesan cheese and chili flakes because I am pizza.",
                pack: 0,
            },
            { text: "Creed.", pack: 0 },
            { text: "Crippling debt.", pack: 0 },
            { text: "Crucifixion.", pack: 0 },
            { text: "Crumpets with the Queen.", pack: 0 },
            { text: "Crystal meth.", pack: 0 },
            { text: "Cuddling.", pack: 0 },
            { text: "Customer service representatives.", pack: 0 },
            { text: "Cybernetic enhancements.", pack: 0 },
            { text: "Daddy issues.", pack: 0 },
            { text: "Daddy's credit card.", pack: 0 },
            { text: "Danny DeVito.", pack: 0 },
            {
                text: "Dark and mysterious forces beyond our control.",
                pack: 0,
            },
            { text: "Darth Vader.", pack: 0 },
            { text: "Date rape.", pack: 0 },
            { text: "Dave Matthews Band.", pack: 0 },
            {
                text: "David Bowie flying in on a tiger made of lightning.",
                pack: 0,
            },
            { text: "David Cameron.", pack: 0 },
            { text: "Dead babies.", pack: 0 },
            { text: "Dead birds everywhere.", pack: 0 },
            { text: "Dead parents.", pack: 0 },
            { text: "Deflowering the princess.", pack: 0 },
            { text: "Dental dams.", pack: 0 },
            { text: "Destroying the evidence.", pack: 0 },
            { text: "Dick Cheney.", pack: 0 },
            {
                text: "Dining with cardboard cutouts of the cast of Friends.",
                pack: 0,
            },
            { text: "Dirty nappies.", pack: 0 },
            { text: "Disco Inferno.", pack: 0 },
            { text: "Diversity.", pack: 0 },
            { text: "Doing crimes.", pack: 0 },
            { text: "Doing the right thing.", pack: 0 },
            { text: "Don Cherry's wardrobe.", pack: 0 },
            { text: "Donald J. Trump.", pack: 0 },
            { text: "Donald Trump's deleted tweets.", pack: 0 },
            { text: "Double rainbows.", pack: 0 },
            { text: "Douchebags on their iPhones.", pack: 0 },
            { text: "Dr. Martin Luther King, Jr.", pack: 0 },
            { text: "Drinking alone.", pack: 0 },
            {
                text: "Drinking out of the toilet and eating garbage.",
                pack: 0,
            },
            { text: "Dropping a baby down the dunny.", pack: 0 },
            {
                text: "Dropping a chandelier on your enemies and riding the rope up.",
                pack: 0,
            },
            { text: "Drowning the kids in the bathtub.", pack: 0 },
            { text: "Druids.", pack: 0 },
            { text: "Drum circles.", pack: 0 },
            { text: "Dry heaving.", pack: 0 },
            { text: "Dwarf tossing.", pack: 0 },
            { text: 'Dwayne "The Rock" Johnson.', pack: 0 },
            {
                text: "Dying but miraculously getting brought back to life.",
                pack: 0,
            },
            { text: "Dying of dysentery.", pack: 0 },
            { text: "Dying.", pack: 0 },
            { text: "Eastern European Turbo-Folk music.", pack: 0 },
            { text: "Eating an albino.", pack: 0 },
            { text: "Eating the last known bison.", pack: 0 },
            { text: "Eating too much of a lamp.", pack: 0 },
            { text: "Ecstasy.", pack: 0 },
            { text: "Edible underpants.", pack: 0 },
            { text: "Elderly Japanese men.", pack: 0 },
            { text: "Electricity.", pack: 0 },
            { text: "Embryonic stem cells.", pack: 0 },
            {
                text: "Emerging from the sea and rampaging through Tokyo.",
                pack: 0,
            },
            { text: "Emma Watson.", pack: 0 },
            { text: "Emotions.", pack: 0 },
            { text: "England.", pack: 0 },
            { text: "Establishing dominance.", pack: 0 },
            { text: "Eternal awesomeness.", pack: 0 },
            { text: "Ethnic cleansing.", pack: 0 },
            { text: "Eugenics.", pack: 0 },
            { text: "Exactly what you'd expect.", pack: 0 },
            { text: "Excalibur.", pack: 0 },
            { text: "Exchanging pleasantries.", pack: 0 },
            { text: "Executing a hostage every hour.", pack: 0 },
            { text: "Existentialists.", pack: 0 },
            { text: "Exorcism.", pack: 0 },
            {
                text: "Expecting a burp and vomiting on the floor.",
                pack: 0,
            },
            { text: "Explosions.", pack: 0 },
            { text: "Extremely tight jeans.", pack: 0 },
            { text: "Extremely tight pants.", pack: 0 },
            { text: "Extremely tight trousers.", pack: 0 },
            { text: "Facebook.", pack: 0 },
            { text: "Fading away into nothingness.", pack: 0 },
            { text: "Faffing about.", pack: 0 },
            { text: "Faith healing.", pack: 0 },
            { text: "Fake tits.", pack: 0 },
            { text: "FALCON PUNCH!!!", pack: 0 },
            { text: "Famine.", pack: 0 },
            { text: "Farting and walking away.", pack: 0 },
            { text: "Fear itself.", pack: 0 },
            { text: "Feeding Rosie O'Donnell.", pack: 0 },
            { text: "Fellowship in Christ.", pack: 0 },
            { text: "Fiery poops.", pack: 0 },
            { text: "Filling my briefcase with business stuff.", pack: 0 },
            { text: "Filling my son with spaghetti.", pack: 0 },
            {
                text: "Filling Sean Hannity with helium and watching him float away.",
                pack: 0,
            },
            { text: "Finger painting.", pack: 0 },
            { text: "Five litres of Special Brew.", pack: 0 },
            { text: "Five-Dollar Footlongs™.", pack: 0 },
            { text: "Flash flooding.", pack: 0 },
            { text: "Flesh-eating bacteria.", pack: 0 },
            { text: "Flightless birds.", pack: 0 },
            { text: "Flying saucers", pack: 0 },
            { text: "Forced sterilization.", pack: 0 },
            { text: "Forgetting the Alamo.", pack: 0 },
            { text: "Former President George W. Bush.", pack: 0 },
            { text: "Four Loko.", pack: 0 },
            { text: "Fox News.", pack: 0 },
            { text: "Fragile masculinity.", pack: 0 },
            { text: "Free samples.", pack: 0 },
            { text: "Friction.", pack: 0 },
            { text: "Friendly fire.", pack: 0 },
            { text: "Friends who eat all your snacks.", pack: 0 },
            { text: "Friends with benefits.", pack: 0 },
            { text: "Full frontal nudity.", pack: 0 },
            { text: "Funky fresh rhymes.", pack: 0 },
            { text: "Gandalf.", pack: 0 },
            { text: "Gandhi.", pack: 0 },
            { text: "Garth Brooks.", pack: 0 },
            { text: "Gary Coleman.", pack: 0 },
            { text: "Gary Glitter.", pack: 0 },
            { text: "Gay animals.", pack: 0 },
            { text: "Gay conversion therapy.", pack: 0 },
            { text: "Geese.", pack: 0 },
            { text: "Genetically engineered super-soldiers.", pack: 0 },
            { text: "Genghis Khan.", pack: 0 },
            { text: "Genuine human connection.", pack: 0 },
            { text: "German Chancellor Angela Merkel.", pack: 0 },
            { text: "German dungeon porn.", pack: 0 },
            { text: "Germans on holiday.", pack: 0 },
            { text: "Getting crushed by a vending machine.", pack: 0 },
            {
                text: "Getting drugs off the street and into my body.",
                pack: 0,
            },
            { text: "Getting drunk on mouthwash.", pack: 0 },
            { text: "Getting into a pretty bad car accident.", pack: 0 },
            {
                text: "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying.",
                pack: 0,
            },
            {
                text: "Getting married, having a few kids, buying some stuff, retiring to Queensland, and dying.",
                pack: 0,
            },
            {
                text: "Getting married, having a few kids, buying some stuff, retiring to the south of France, and dying.",
                pack: 0,
            },
            { text: "Getting naked and watching Nickelodeon.", pack: 0 },
            { text: "Getting naked and watching Play School.", pack: 0 },
            { text: "Getting pregnant again.", pack: 0 },
            { text: "Getting really high.", pack: 0 },
            {
                text: "Getting wed, having a few kids, taking some pictures, retiring to the south of France, and dying.",
                pack: 0,
            },
            { text: "Ghosts.", pack: 0 },
            { text: "Girls who shouldn't go wild.", pack: 0 },
            { text: "Girls.", pack: 0 },
            { text: "Giving 110%.", pack: 0 },
            { text: "Giving birth to the Antichrist.", pack: 0 },
            { text: "Gladiatorial combat.", pack: 0 },
            { text: "Glassing a wanker.", pack: 0 },
            {
                text: "Glenn Beck being harried by a swarm of buzzards.",
                pack: 0,
            },
            { text: "Global warming.", pack: 0 },
            { text: "Goats eating cans.", pack: 0 },
            { text: "Goblins.", pack: 0 },
            { text: "God.", pack: 0 },
            { text: "Going around sniffing people's armpits.", pack: 0 },
            { text: "Good-natured, fun-loving Aussie racism.", pack: 0 },
            { text: "Grandma.", pack: 0 },
            { text: "Grandpa's bald spot.", pack: 0 },
            { text: "Grassroots support", pack: 0 },
            { text: "Grave robbing.", pack: 0 },
            { text: "Growing a pair.", pack: 0 },
            { text: "Guys who don't call.", pack: 0 },
            { text: "Haggis.", pack: 0 },
            { text: "Half a kilo of pure China White heroin.", pack: 0 },
            { text: "Harry Potter erotica.", pack: 0 },
            {
                text: "Having big dreams but no realistic way to achieve them.",
                pack: 0,
            },
            { text: "Having sex for the first time.", pack: 0 },
            { text: "Having sex with every man in Winnipeg.", pack: 0 },
            { text: "Having sloppy sex as your dog watches.", pack: 0 },
            { text: "Heartwarming orphans.", pack: 0 },
            { text: "Heath Ledger.", pack: 0 },
            { text: "Her Majesty, Queen Elizabeth II.", pack: 0 },
            { text: "Her Royal Highness, Queen Elizabeth II.", pack: 0 },
            { text: "Heritage minutes.", pack: 0 },
            { text: "hermaphroditical Italian pictures", pack: 0 },
            { text: "Heroin.", pack: 0 },
            { text: "Heteronormativity.", pack: 0 },
            { text: "Hillary Clinton's favorite nipple clamps", pack: 0 },
            { text: "Hip hop jewels.", pack: 0 },
            { text: "Hipsters.", pack: 0 },
            { text: "Historically black colleges.", pack: 0 },
            {
                text: "Holding down a child and farting all over him.",
                pack: 0,
            },
            { text: "Homeless people.", pack: 0 },
            { text: "Hope.", pack: 0 },
            { text: "Hormone injections.", pack: 0 },
            { text: "Horrifying laser hair removal accidents.", pack: 0 },
            { text: "Horse meat.", pack: 0 },
            { text: "Hospice care.", pack: 0 },
            { text: "Hot cheese.", pack: 0 },
            { text: "Hot people.", pack: 0 },
            { text: "How amazing it is to be on mushrooms.", pack: 0 },
            { text: "How awesome it is to be white.", pack: 0 },
            { text: "However much weed £20 can buy.", pack: 0 },
            { text: "Huge biceps.", pack: 0 },
            { text: "Hulk Hogan.", pack: 0 },
            { text: "Hunting accidents.", pack: 0 },
            {
                text: "Hurling one's body down a hill in pursuit of a wheel of cheese.",
                pack: 0,
            },
            { text: "Hurricane Katrina.", pack: 0 },
            { text: "Hurting those closest to me.", pack: 0 },
            { text: "I'm friends with your dad on Facebook.", pack: 0 },
            { text: "Ice.", pack: 0 },
            { text: "Illegal immigrants.", pack: 0 },
        ],
        black: [
            {
                text: "_ is a sure sign of mankind's decline.",
                pick: 1,
                pack: 0,
            },
            {
                text: "_ would only happen in my worst nightmares.",
                pick: 1,
                pack: 0,
            },
            { text: "_: good to the last drop.", pick: 1, pack: 0 },
            { text: "_: kid tested, mother approved.", pick: 1, pack: 0 },
            {
                text: "_: Once you pop, the fun don't stop!",
                pick: 1,
                pack: 0,
            },
            {
                text: "_? Oh yeah. There's porn about that.",
                pick: 1,
                pack: 0,
            },
            { text: "_? There's an app for that.", pick: 1, pack: 0 },
            { text: "_? Yeah, nah.", pick: 1, pack: 0 },
            {
                text: "_. Awesome in theory, kind of a mess in practice.",
                pick: 1,
                pack: 0,
            },
            { text: "_. Betcha can't have just one!", pick: 1, pack: 0 },
            { text: "_. High five, bro.", pick: 1, pack: 0 },
            { text: "_. It's a trap!", pick: 1, pack: 0 },
            { text: "_. That was so metal.", pick: 1, pack: 0 },
            { text: "_. That's how I want to die.", pick: 1, pack: 0 },
            {
                text: "_. The best way to spice up your sex life.",
                pick: 1,
                pack: 0,
            },
            {
                text: "★✰✰✰✰ Do NOT go here! Found _ in my Kung Pao chicken!",
                pick: 1,
                pack: 0,
            },
            { text: "50% of all marriages end in _.", pick: 1, pack: 0 },
            {
                text: "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "A romantic candlelit dinner would be incomplete without _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "A romantic candlelit dinner would be incomplete without _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "A romantic, candlelit dinner would be incomplete without _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "A successful job interview begins with a firm handshake and ends with _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "After eight years in the White House, how is Obama finally letting loose?",
                pick: 1,
                pack: 0,
            },
            {
                text: "After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "After Hurricane Katrina, Sean Penn brought _ to all the people of New Orleans.",
                pick: 1,
                pack: 0,
            },
            {
                text: "After the earthquake, Sean Penn brought _ to the people of Haiti.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Air Canada guidelines now prohibit _ on airplanes.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Airport security guidelines now prohibit _ on airplanes.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Alternative medicine is now embracing the curative powers of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "And what did you bring for show and tell?",
                pick: 1,
                pack: 0,
            },
            {
                text: "Anthropologists have recently discovered a primitive tribe that worships _.",
                pick: 1,
                pack: 0,
            },
            { text: "Arby's: We Have _.", pick: 1, pack: 0 },
            {
                text: "As my New Year's resolution, I vow to give up _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "As the mom of five rambunctious boys, I'm no stranger to _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "As the mum of five rambunctious boys, I'm no stranger to _.",
                pick: 1,
                pack: 0,
            },
            { text: "Betcha can't have just one!", pick: 1, pack: 0 },
            { text: "BILLY MAYS HERE FOR _.", pick: 1, pack: 0 },
            {
                text: "Bravo's new reality show features eight washed-up celebrities living with _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Brought to you by Bud Light®, the Official Beer of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Brought to you by Molson Canadian, the Official Beer of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "But before I kill you, Mr. Bond, I must show you _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Channel 5's new reality show features eight washed-up celebrities living with _.",
                pick: 1,
                pack: 0,
            },
            {
                text: 'Channel 9 is pleased to present its new variety show, "Hey Hey It\'s _."',
                pick: 1,
                pack: 0,
            },
            { text: "Charlie and the chocolate _.", pick: 1, pack: 0 },
            {
                text: 'Check me out, yo! I call this dance move "_."',
                pick: 1,
                pack: 0,
            },
            { text: "Click Here for _!!!", pick: 1, pack: 0 },
            {
                text: "Coming this season, Samuel Beckett's classic existential play: Waiting for _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Coming to Broadway this season, _: The Musical.",
                pick: 1,
                pack: 0,
            },
            {
                text: 'Coming to theaters this holiday season, "Star Wars: The Rise of _."',
                pick: 1,
                pack: 0,
            },
            {
                text: "Crikey! I've never seen _ like this before! Let's get a bit closer.",
                pick: 1,
                pack: 0,
            },
            { text: "Daddy, why is mommy crying?", pick: 1, pack: 0 },
            { text: "Daddy, why is mummy crying?", pick: 1, pack: 0 },
            {
                text: "Dear Abby, I'm having some trouble with _ and would like your advice.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Dear Agony Aunt, I'm having some trouble with _ and I need your advice.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Doctor, you've gone too far! The human body wasn't meant to withstand that amount of _!",
                pick: 1,
                pack: 0,
            },
            {
                text: "Dude, do not go in that bathroom. There's _ in there.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Dude, do not go in that washroom. There's _ in there.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Due to a PR fiasco, Walmart no longer offers _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "During his childhood, Salvador Dali produced hundreds of paintings of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: 'During his short-lived boxing career, the Messiah fought under the name Jesus "_" Christ.',
                pick: 1,
                pack: 0,
            },
            {
                text: "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "During sex, I like to think about _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Finally! A service that delivers _ right to your door.",
                pick: 1,
                pack: 0,
            },
            {
                text: "For my turn, I will spend four gold and allocate all three workers to _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Fun tip! When your man asks you to go down on him, try surprising him with _ instead.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Future historians will agree that _ marked the beginning of America's decline.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Here is the church\nHere is the steeple\nOpen the doors\nAnd there is _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Hey guys, welcome to Boston Pizza! Would you like to start the night off right with _?",
                pick: 1,
                pack: 0,
            },
            {
                text: "Hey guys, welcome to Chili's! Would you like to start the night off right with _?",
                pick: 1,
                pack: 0,
            },
            {
                text: "Hey guys, welcome to Sizzler! Would you like to start the night off right with _?",
                pick: 1,
                pack: 0,
            },
            {
                text: "Hey guys, welcome to TGIF! Would you like to start the night off right with _?",
                pick: 1,
                pack: 0,
            },
            {
                text: "Hey Reddit! I'm _. Ask me anything.",
                pick: 1,
                pack: 0,
            },
            {
                text: "How am I maintaining my relationship status?",
                pick: 1,
                pack: 0,
            },
            { text: "How did I lose my virginity?", pick: 1, pack: 0 },
            {
                text: "I do not know with what weapons World War III will be fought, but World War IV will be fought with _.",
                pick: 1,
                pack: 0,
            },
            { text: "I drink to forget _.", pick: 1, pack: 0 },
            {
                text: "I get by with a little help from _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "I got 99 problems, but _ ain't one.",
                pick: 1,
                pack: 0,
            },
            {
                text: "I know when that hotline bling, that can only mean one thing: _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "I learned the hard way that you can't cheer up a grieving friend with _.",
                pick: 1,
                pack: 0,
            },
            { text: "I spy with my little eye _.", pick: 1, pack: 0 },
            {
                text: "I wish I hadn't lost the instruction manual for _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "I'm going on a cleanse this week. Nothing but kale juice and _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "I'm Lebron James, and when I'm not slamming dunks, I love _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "I'm no doctor, but I'm pretty sure what you're suffering from is called \"_.\"",
                pick: 1,
                pack: 0,
            },
            {
                text: "I'm sorry, Professor, but I couldn't complete my homework because of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "I'm sorry, Sir, but I couldn't complete my homework because of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "I'm not like the rest of you. I'm too rich and busy for _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "If you can't be with the one you love, love _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "IF you like _, YOU MIGHT BE A REDNECK.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?",
                pick: 1,
                pack: 0,
            },
            {
                text: "In 1,000 years, when paper money is but a distant memory, _ will be our currency.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In an attempt to reach a wider audience, the National Museum of Australia has opened an interactive exhibit on _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In Australia, _ is twice as big and twice as deadly.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In Belmarsh Prison, word is you can trade 200 cigarettes for _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In her latest feature-length film, Tracy Beaker struggles with _ for the first time.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In his new self-produced album, Kanye West raps over the sounds of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In L.A. County Jail, word is you can trade 200 cigarettes for _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In Michael Jackson's final moments, he thought about _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In Rome, there are whisperings that the Vatican has a secret room devoted to _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In the seventh circle of Hell, sinners must endure _ for all eternity.",
                pick: 1,
                pack: 0,
            },
            {
                text: "In your Best-Man speech, I'd talk about when we found ourselves _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Instead of coal, Father Christmas now gives the bad children _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Instead of coal, Santa now gives the bad children _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Introducing X-Treme Baseball! It's like baseball, but with _!",
                pick: 1,
                pack: 0,
            },
            { text: "It's a trap!", pick: 1, pack: 0 },
            {
                text: 'Just once, I\'d like to hear you say "Thanks, Mom. Thanks for _."',
                pick: 1,
                pack: 0,
            },
            {
                text: 'Just once, I\'d like to hear you say "Thanks, Mum. Thanks for _."',
                pick: 1,
                pack: 0,
            },
            {
                text: "Just saw this upsetting video! Please retweet!! #stop_",
                pick: 1,
                pack: 0,
            },
            {
                text: "Kids, I don't need drugs to get high. I'm high on _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Life for Aboriginal people was forever changed when the white man introduced them to _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Life for American Indians was forever changed when the White Man introduced them to _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Life was difficult for cavemen before _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Lovin' you is easy 'cause you're _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Major League Baseball has banned _ for giving players an unfair advantage.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Mate, do not go in that bathroom. There's _ in there.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Mate, do not go in that toilet. There's _ in there.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Maybe she's born with it. Maybe it's _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Men's Wearhouse: You're gonna like _. I guarantee it.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Military historians remember Alexander the Great for his brilliant use of _ against the Persians.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Money can't buy me love, but it can buy me _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Mr. and Mrs. Diaz, we called you in because we're concerned about Cynthia. Are you aware that your daughter is _?",
                pick: 1,
                pack: 0,
            },
            {
                text: "MTV's new reality show features eight washed-up celebrities living with _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "My fellow Americans: Before this decade is out, we will have _ on the moon!",
                pick: 1,
                pack: 0,
            },
            {
                text: "My mom is so happy when I visit, but I'm only there to be _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "My plan for world domination begins with _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Next from J.K. Rowling: Harry Potter and the Chamber of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Next from J.K. Rowling: Harry Potter and the chamber of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Next on ESPN2: The World Series of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Next on Eurosport: The World Championship of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Next on Nine's Wide World of Sports: The World Championship of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Next on Sky Sports: The World Champsion of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Next on Sky Sports: The World Champsion of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Next on TSN: The World Series of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Next up on Channel 4: Ramsay's _ Nightmares.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Now at the National Museum of Australia: an interactive exhibit on _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Now at the Natural History Museum: an interactive exhibit on _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Now at the Royal Ontario Museum: an interactive exhibit on _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Now at the Smithsonian: an interactive exhibit on _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "O Canada, we stand on guard for _.",
                pick: 1,
                pack: 0,
            },
            { text: "Oi! Show us _!", pick: 1, pack: 0 },
            { text: "Old MacDonald had _. E-I-E-I-O.", pick: 1, pack: 0 },
            { text: "Only you can prevent _.", pick: 1, pack: 0 },
            {
                text: "Penalty! _: that's 5 minutes in the box!",
                pick: 1,
                pack: 0,
            },
            {
                text: "Qantas now prohibits _ on airplanes.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Studies show that lab rats navigate mazes 50% faster after being exposed to _.",
                pick: 1,
                pack: 0,
            },
            { text: "Thank God for alcohol and _.", pick: 1, pack: 0 },
            {
                text: "The blind date was going horribly until we discovered our shared interest in _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "The class field trip was completely ruined by _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "The Four Horsemen of the Apocalypse: Pestilence, War, Famine, and _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "The hills are alive with the sound of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "The neighborhood kid didn't use snow for their snowman, they used _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "The new Chevy Tahoe. With the power and space to take _ everywhere you go.",
                pick: 1,
                pack: 0,
            },
            {
                text: "The school excursion was completely ruined by _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "The school field trip was completely ruined by _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "The school trip was completely ruined by _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "The secret to a lasting marriage is communication, communication, and _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "The Smithsonian Museum of Natural History has just opened an interactive exhibit on _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "The TFL apologizes for the delay in train service due to _.",
                pick: 1,
                pack: 0,
            },
            {
                text: 'The theme for next year\'s Eurovision Song Contest is "We are _."',
                pick: 1,
                pack: 0,
            },
            {
                text: "The U.S. has begun airdropping _ to the children of Afghanistan.",
                pick: 1,
                pack: 0,
            },
            {
                text: "This is the way the world ends\nThis is the way the world ends\nNot with a bang but with _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "This is your pilot speaking. Please prepare for _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "This season at Steppenwolf, Samuel Beckett's classic existential play: Waitng for _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "This season at the old Vic, Samuel Beckett's classic existential play: Waitng for _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "This season at the Princess of Wales Theatre, Samuel Beckett's classic existential play: Waiting for _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "This season at the Sydney Opera House, Samuel Beckett's classic existential play: Waiting for _.",
                pick: 1,
                pack: 0,
            },
            {
                text: 'Today on Jerry Springer: "Help! My son is _!"',
                pick: 1,
                pack: 0,
            },
            {
                text: 'Today on Maury: "Help! My son is _!"',
                pick: 1,
                pack: 0,
            },
            {
                text: 'Today on The Jeremy Kyle Show: "Help! My son is _!"',
                pick: 1,
                pack: 0,
            },
            {
                text: "Tonight's top story: What you don't know about _ could kill you.",
                pick: 1,
                pack: 0,
            },
            {
                text: "TSA guidelines now prohibit _ on airplanes.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Turns out that _-Man was neither the hero we needed nor wanted.",
                pick: 1,
                pack: 0,
            },
            {
                text: "Uh, hey guys, I know this was my idea, but I'm having serious doubts about _.",
                pick: 1,
                pack: 0,
            },
            { text: "UKIP: Putting _ First!", pick: 1, pack: 0 },
            { text: "War! What is it good for?", pick: 1, pack: 0 },
            {
                text: "Well if you'll excuse me, gentlemen, I have a date with _.",
                pick: 1,
                pack: 0,
            },
            { text: "What am I giving up for Lent?", pick: 1, pack: 0 },
            {
                text: "What are my parents hiding from me?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What are school administrators using to curb rampant teenage pregnancy?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What broke up the original Wiggles?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What brought the orgy to a grinding halt?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What did I bring back from Amsterdam?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What did I bring back from Bali?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What did I bring back from Mexico?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What did the US airdrop to the children of Afghanistan?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What did Vin Diesel eat for dinner?",
                pick: 1,
                pack: 0,
            },
            { text: "What do old people smell like?", pick: 1, pack: 0 },
            { text: "What does Dick Cheney prefer?", pick: 1, pack: 0 },
            {
                text: "What don't you want to find in your Chinese food?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What don't you want to find in your doner kebab?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What don't you want to find in your Kung Pao chicken?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What don't you want to find in your Mongolian beef?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What ended my last relationship?",
                pick: 1,
                pack: 0,
            },
            { text: "What gets better with age?", pick: 1, pack: 0 },
            {
                text: "What gives me uncontrollable gas?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What has been making life difficult at the nudist colony?",
                pick: 1,
                pack: 0,
            },
            { text: "What helps Barack Obama unwind?", pick: 1, pack: 0 },
            { text: "What helps Obama unwind?", pick: 1, pack: 0 },
            {
                text: "What is Batman's guilty pleasure?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What is George W. Bush thinking about right now?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What kept Margaret Thatcher busy in her waning years?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What left this stain on my couch?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What made my first kiss so awkward?",
                pick: 1,
                pack: 0,
            },
            { text: "What makes life worth living?", pick: 1, pack: 0 },
            {
                text: "What makes me a true blue Aussie?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What never fails to liven up the party?",
                pick: 1,
                pack: 0,
            },
            { text: "What will always get you laid?", pick: 1, pack: 0 },
            {
                text: "What will I bring back in time to convince people that I am a powerful wizard?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What would grandma find disturbing, yet oddly charming?",
                pick: 1,
                pack: 0,
            },
            { text: "What's a girl's best friend?", pick: 1, pack: 0 },
            { text: "What's my anti-drug?", pick: 1, pack: 0 },
            { text: "What's my secret power?", pick: 1, pack: 0 },
            {
                text: "What's Teach for America using to inspire inner city students to succeed?",
                pick: 1,
                pack: 0,
            },
            { text: "What's that smell?", pick: 1, pack: 0 },
            { text: "What's that sound?", pick: 1, pack: 0 },
            {
                text: "What's the Canadian government using to inspire rural students to succeed?",
                pick: 1,
                pack: 0,
            },
            { text: "What's the crustiest?", pick: 1, pack: 0 },
            { text: "What's the most emo?", pick: 1, pack: 0 },
            { text: "What's the new fad diet?", pick: 1, pack: 0 },
            {
                text: "What's the next Happy Meal® toy?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What's the next superhero/sidekick duo?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What's there a ton of in heaven?",
                pick: 1,
                pack: 0,
            },
            {
                text: "What's there a tonne of in heaven?",
                pick: 1,
                pack: 0,
            },
            {
                text: "When all else fails, I can always masturbate to _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "When I am a billionare, I shall erect a 20-meter statue to commemorate _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "When I am a billionare, I shall erect a 20-metre statue to commemorate _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "When I am a billionare, I shall erect a 50-foot statue to commemorate _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "When I am President of the United States, I will create the Department of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "When I am President, I will create the Department of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "When I am Prime Minister of Canada, I will create the Department of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "When I am Prime Minister of Canada, I will create the Ministry of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "When I am Prime Minister, I will create the Department of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "When I am Prime Minister, I will create the Department of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "When I am Prime Minister, I will create the Ministry of _.",
                pick: 1,
                pack: 0,
            },
            {
                text: "When I pooped, what came out of my butt?",
                pick: 1,
                pack: 0,
            },
            {
                text: "When I'm pooping, I like to think about _.",
                pick: 1,
                pack: 0,
            },
        ],
        official: true,
    },
];

module.exports = cards;
